# services:
#   # PHP
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: raccourcisseur_app
#     restart: unless-stopped
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#       - ./storage:/var/www/storage
#       - ./database/database.sqlite:/var/www/database/database.sqlite
#     networks:
#       - raccourcisseur_network
#     depends_on:
#       - redis

#   # Nginx
#   nginx:
#     image: nginx:alpine
#     container_name: raccourcisseur_nginx
#     restart: unless-stopped
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www
#       - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#     networks:
#       - raccourcisseur_network
#     depends_on:
#       - app

#   # Redis
#   redis:
#     image: redis:alpine
#     container_name: raccourcisseur_redis
#     restart: unless-stopped
#     ports:
#       - "6379:6379"
#     networks:
#       - raccourcisseur_network

#   # Laravel Queue Worker
#   queue:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: raccourcisseur_queue
#     restart: unless-stopped
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#       - ./database/database.sqlite:/var/www/database/database.sqlite
#     command: php artisan queue:work --tries=3 --sleep=3
#     networks:
#       - raccourcisseur_network
#     depends_on:
#       - app
#       - redis

# networks:
#   raccourcisseur_network:
#     driver: bridge
